color0 #32302f
color1 #ea6962
color2 #a9b665
color3 #d8a657
color4 #7daea3
color5 #d3869b
color6 #89b482
color7 #d4be98
color8 #928374
color9 #ea6962
color10 #a9b665
color11 #d8a657
color12 #7daea3
color13 #d3869b
color14 #89b482
color15 #ddc7a1

cursor                #d4be98
cursor_text_color     #282828
background            #282828
foreground            #d4be98
selection_foreground  #ddc7a1
selection_background  #45403d
active_border_color   #a9b665
inactive_border_color #45403d
url_color             #a9b665

active_tab_foreground   #282828
active_tab_background   #a9b665
inactive_tab_foreground #a89984
inactive_tab_background #45403d
cursor_trail_color      #a89984
