gui:
  nerdFontsVersion: "3"
  showFileTree: true
git:
  diffRenderers:
    - colorArg: always
      command: delta --dark --paging=never
  log:
    order: topo-order
    showGraph: always
os:
  editPreset: nvim-remote
customCommands:
  - key: b
    command: gh browse
    context: files
  - key: b
    command: 'gh browse "{{.SelectedLocalCommit.Sha}}"'
    context: commits
confirmOnQuit: false
