---@type vim.lsp.Config
return {
	cmd = { "gopls" },
	filetypes = { "go", "gomod", "gowork", "gotmpl" },
	root_markers = { "go.work", "go.mod", ".git" },
	settings = {
		gopls = {
			templateExtensions = { "tpl", "yaml", "tmpl", "tmpl.html" },
			gofumpt = true,
			usePlaceholders = true,
			completeUnimported = true,
			completeFunctionCalls = true,
			semanticTokens = true,
			vulncheck = "Imports",
			codelenses = {
				generate = true,
				gc_details = false,
				regenerate_cgo = true,
				run_govulncheck = true,
				test = true,
				tidy = true,
				upgrade_dependency = true,
				vendor = true,
			},
			analyses = {
				nilness = true,
				unusedresult = true,
				unusedparams = true,
				unusedwrite = true,
				useany = true,
				unreachable = true,
				shadow = true,
				composites = true,
			},
			hints = {
				assignVariableTypes = true,
				compositeLiteralFields = true,
				compositeLiteralTypes = true,
				constantValues = true,
				functionTypeParameters = true,
				parameterNames = true,
				rangeVariableTypes = true,
			},
			staticcheck = true,
			directoryFilters = { "-.git", "-.vscode", "-node_modules" },
		},
	},
}
